### Importation des bibliothéques et de la dataset Loan

In [26]:
import pandas as pd 
import numpy as np
import seaborn as sns

In [27]:
df_loan = pd.read_csv("loan_data.csv")
df_loan.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y


### Description des colonnes

Informations personnelles

- Sexe (_Gender_) : indique si le demandeur est un homme ou une femme.
- État civil (_Married_) : indique l'état civil du demandeur (Oui ou Non).
- Personnes à charge (_Dependents_) : nombre de personnes dont le demandeur assure la prise en charge financière (par exemple, 0, 1, 2, 3 ou plus).
- Formation (_Education_): niveau d'études du demandeur (diplômé de l'enseignement supérieur ou étudiant de premier cycle).
- Indépendant (_Self_Employed_) : indique si le demandeur exerce une activité indépendante (Oui ou Non). 

Informations financières 

- Revenu du demandeur (_ApplicantIncome_): montant des revenus du demandeur principal.
- Revenu du codemandeur (_CoapplicantIncome_): montant des revenus du cosignataire ou du partenaire.
- Montant du prêt (_LoanAmpount_): montant total demandé pour le prêt (généralement en milliers).
- Durée du prêt (Loan_Amount_Term  ): durée accordée pour rembourser le prêt (généralement en mois, par exemple 360 pour 30 ans).
- Historique de crédit (_Credit_History_): un historique des antécédents de remboursement des dettes (1 signifie un bon crédit, 0 signifie un mauvais crédit). 

Localisation et résultat 

- Zone de la propriété  (_Property_Area_) : le type de zone où se trouve la propriété (urbaine, périurbaine ou rurale).
- Statut du prêt (_Loan_Status_) : la décision finale concernant le prêt (Y pour « approuvé », N pour « refusé »). Il s’agit de la variable cible que vous essayez de prédire.



### Dimension du dataset

In [28]:
df_loan.shape

(981, 13)

### Information sur les types des données

In [29]:
df_loan.info()

<class 'pandas.DataFrame'>
RangeIndex: 981 entries, 0 to 980
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            981 non-null    str    
 1   Gender             957 non-null    str    
 2   Married            978 non-null    str    
 3   Dependents         956 non-null    str    
 4   Education          981 non-null    str    
 5   Self_Employed      926 non-null    str    
 6   ApplicantIncome    981 non-null    int64  
 7   CoapplicantIncome  981 non-null    float64
 8   LoanAmount         954 non-null    float64
 9   Loan_Amount_Term   961 non-null    float64
 10  Credit_History     902 non-null    float64
 11  Property_Area      981 non-null    str    
 12  Loan_Status        614 non-null    str    
dtypes: float64(4), int64(1), str(8)
memory usage: 99.8 KB


### Variables numériques

In [30]:
df_loan.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,981.000000,981.000000,954.000000,961.000000,902.000000
mean,5179.795107,1601.916330,142.511530,342.201873,0.835920
std,5695.104533,2718.772806,77.421743,65.100602,0.370553
min,0.000000,0.000000,9.000000,6.000000,0.000000
25%,2875.000000,0.000000,100.000000,360.000000,1.000000
50%,3800.000000,1110.000000,126.000000,360.000000,1.000000
75%,5516.000000,2365.000000,162.000000,360.000000,1.000000
max,81000.000000,41667.000000,700.000000,480.000000,1.000000


In [97]:
print("Doublons :", df_loan.duplicated().sum())
for col in df_loan.select_dtypes(include='object').columns:
    print(col, ":", df_loan[col].unique())

Doublons : 0
Loan_ID : <StringArray>
['LP001002', 'LP001003', 'LP001005', 'LP001006', 'LP001008', 'LP001011',
 'LP001013', 'LP001014', 'LP001018', 'LP001020',
 ...
 'LP002952', 'LP002954', 'LP002962', 'LP002965', 'LP002969', 'LP002971',
 'LP002975', 'LP002980', 'LP002986', 'LP002989']
Length: 981, dtype: str
Gender : <StringArray>
['Male', 'Female', nan]
Length: 3, dtype: str
Married : <StringArray>
['No', 'Yes', nan]
Length: 3, dtype: str
Dependents : <StringArray>
['0', '1', '2', '3+', nan]
Length: 5, dtype: str
Education : <StringArray>
['Graduate', 'Not Graduate']
Length: 2, dtype: str
Self_Employed : <StringArray>
['No', 'Yes', nan]
Length: 3, dtype: str
Property_Area : <StringArray>
['Urban', 'Rural', 'Semiurban']
Length: 3, dtype: str
Loan_Status : <StringArray>
['Y', 'N', nan]
Length: 3, dtype: str


/tmp/ipykernel_83/1515035218.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df_loan.select_dtypes(include='object').columns:


### Variables catégorielles

In [31]:
df_loan.describe(include=['str'])

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,Property_Area,Loan_Status
count,981,957,978,956,981,926,981,614
unique,981,2,2,4,2,2,3,2
top,LP001002,Male,Yes,0,Graduate,No,Semiurban,Y
freq,1,775,631,545,763,807,349,422


###  Visualisation des données (prétaitrement)



### Crédit accordé et refusé


In [32]:
df_loan["Loan_Status"].value_counts(normalize=True)

Loan_Status
Y    0.687296
N    0.312704
Name: proportion, dtype: float64

### Vérification du status Y ou N

In [33]:
pd.crosstab(df_loan["Credit_History"], df_loan["Loan_Status"])

Loan_Status,N,Y
Credit_History,,
0.0,82,7
1.0,97,378


**Commentaire :**
Y représente bien prêt accordé car la majorité qui ont un bon historique de 1.0 on un Y (378) contre 82 N pour ceux qui ont un mauvais historique de 0.0 et seulement 7 Y.


### Revenu du demandeur selon le statut de prêt 

In [34]:
df_loan.groupby("Loan_Status")["ApplicantIncome"].describe()

,count,mean,std,min,25%,50%,75%,max
Loan_Status,,,,,,,,
N,192.0,5446.078125,6819.558528,150.0,2885.0,3833.5,5861.25,81000.0
Y,422.0,5384.068720,5765.441615,210.0,2877.5,3812.5,5771.50,63337.0


### Zone géographique vs status

In [35]:
pd.crosstab(df_loan["Property_Area"], df_loan["Loan_Status"], normalize='index')

Loan_Status,N,Y
Property_Area,,
Rural,0.385475,0.614525
Semiurban,0.231760,0.768240
Urban,0.341584,0.658416


### Niveau d'études vs statut

In [36]:
pd.crosstab(df_loan["Education"], df_loan["Loan_Status"], normalize='index')

Loan_Status,N,Y
Education,,
Graduate,0.291667,0.708333
Not Graduate,0.388060,0.611940


**Commentaire** :

Parmi les variables explorées, Credit_History se distingue nettement comme le facteur le plus déterminant : les demandeurs avec un bon historique de crédit obtiennent très majoritairement leur prêt, tandis que ceux avec un mauvais historique sont très majoritairement refusés. l'écart entre les deux groupes est le plus marqué de toutes les variables étudiées.

Property_Area (zone géographique) montre un effet réel mais plus modéré : les demandeurs en zone semi-urbaine semblent avoir un taux d'accord plus favorable que ceux en zone rurale, la zone urbaine se situant entre les deux.

Education (niveau d'études) a également une influence, mais plus limitée : les diplômés (Graduate) affichent un taux d'accord légèrement supérieur aux non-diplômés (Not Graduate), sans que l'écart soit aussi marqué que pour l'historique de crédit.

En résumé : Credit_History apparaît comme le facteur dominant, suivi par Property_Area puis Education, dont l'influence est plus secondaire.

### Visualisations histplot 

In [37]:
sns.histplot(df_loan['ApplicantIncome'])

<Axes: xlabel='ApplicantIncome', ylabel='Count'>

On comprends avec cet histplot que le revenu demandeur est sensiblement accru entre 0 et 10000, avec quelques exceptions entre des revenus demandeurs plus important.


In [38]:
sns.histplot(df_loan['LoanAmount'])

<Axes: xlabel='LoanAmount', ylabel='Count'>

Le montant du prêt possède un pic entre 100 et 200.

In [39]:
sns.histplot(df_loan['Loan_Amount_Term'])

<Axes: xlabel='Loan_Amount_Term', ylabel='Count'>

### Corrélation entre variables numériques

In [95]:
df_corr_num = df_loan.select_dtypes(include='number').corr()
df_corr_num

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
ApplicantIncome,1.000000,-0.114247,0.551811,-0.023089,0.023378
CoapplicantIncome,-0.114247,1.000000,0.179228,-0.043860,-0.027253
LoanAmount,0.551811,0.179228,1.000000,0.055636,-0.008235
Loan_Amount_Term,-0.023089,-0.043860,0.055636,1.000000,-0.020439
Credit_History,0.023378,-0.027253,-0.008235,-0.020439,1.000000


In [96]:
sns.heatmap(df_corr_num, annot=True, cmap='coolwarm')
plt.title("Corrélation entre variables numériques")
plt.show()

### Identification des valeurs manquantes

In [43]:
df_loan.isnull().sum()

Loan_ID                0
Gender                24
Married                3
Dependents            25
Education              0
Self_Employed         55
ApplicantIncome        0
CoapplicantIncome      0
LoanAmount            27
Loan_Amount_Term      20
Credit_History        79
Property_Area          0
Loan_Status          367
dtype: int64

### Identification des valeurs aberrantes

In [44]:
sns.boxplot(df_loan['ApplicantIncome'])

<Axes: ylabel='ApplicantIncome'>

In [45]:
sns.boxplot(df_loan['CoapplicantIncome'])

<Axes: ylabel='CoapplicantIncome'>

In [46]:
sns.boxplot(df_loan['Loan_Amount_Term'])

<Axes: ylabel='Loan_Amount_Term'>

In [47]:
sns.boxplot(df_loan['LoanAmount'])

<Axes: ylabel='LoanAmount'>

** Commentaire** :Les boxplots révèlent des valeurs extrêmes sur ApplicantIncome et LoanAmount, cohérentes avec la réalité (hauts revenus, gros prêts). Elles sont conservées : la Random Forest et l'Arbre de Décision sont peu sensibles aux outliers, et la standardisation appliquée pour la Régression Logistique limite leur impact.

## Séparation des lignes avec statut connu / inconnu

In [48]:
# On garde uniquement les lignes où Loan_Status est renseigné pour l'entraînement
df_train_valid = df_loan[df_loan["Loan_Status"].notna()]
df_a_predire = df_loan[df_loan["Loan_Status"].isna()]

print(df_train_valid.shape)
print(df_a_predire.shape)

(614, 13)
(367, 13)


## Split train/test

In [49]:
from sklearn.model_selection import train_test_split

X = df_train_valid.drop(columns=["Loan_Status", "Loan_ID"])
y = df_train_valid["Loan_Status"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

## Traitement des valeurs manquantes  variables catégorielles (mode)

In [50]:
df_loan.select_dtypes(include=['object', 'str', 'category']).isnull().sum()         #nb de valeurs manquantes par colonne catégorielle

Loan_ID            0
Gender            24
Married            3
Dependents        25
Education          0
Self_Employed     55
Property_Area      0
Loan_Status      367
dtype: int64

In [51]:
colonnes_cibles = ['Gender','Married','Dependents','Self_Employed']
non_renseigne = "Inconnu"

for col in colonnes_cibles:
    X_train[col] = X_train[col].fillna(non_renseigne)
    X_test[col] = X_test[col].fillna(non_renseigne)

## Traitement des valeurs manquantes  variables numériques (médiane)

In [52]:
chiffres = ["LoanAmount", "Loan_Amount_Term", "Credit_History"]

for chiffre in chiffres:
    mediane = X_train[chiffre].median()
    print("avant :", X_train[chiffre].isna().sum(), X_test[chiffre].isna().sum())
    X_train[chiffre] = X_train[chiffre].fillna(mediane)
    X_test[chiffre] = X_test[chiffre].fillna(mediane)
    print("après :", X_train[chiffre].isna().sum(), X_test[chiffre].isna().sum())
    print("---")



avant : 20 2
après : 0 0
---
avant : 12 2
après : 0 0
---
avant : 43 7
après : 0 0
---


In [53]:
X_train[(X_train["Credit_History"]!=0) & (X_train['Credit_History']!=1)]

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area


## Encodage des variables catégorielles

In [54]:
## Encodage des variables catégorielles
colonnes_a_encoder = ["Gender", "Married", "Dependents", "Education", "Self_Employed", "Property_Area"]

X_train = pd.get_dummies(X_train, columns=colonnes_a_encoder, drop_first=True)
X_test = pd.get_dummies(X_test, columns=colonnes_a_encoder, drop_first=True)

**Commentaire :** aucun des modèles ne peut travailler directement avec du texte (`"Male"`, `"Yes"`, `"Urban"`...). 
On transforme donc chaque variable catégorielle en colonnes numériques 0/1 via `pd.get_dummies`. On utilise `drop_first=True` pour éviter la redondance : avec 2 catégories (ex. `Married`), une seule colonne (`Married_Yes`) suffit à représenter l'information. Si elle vaut 0, on sait que c'est "No" sans avoir besoin d'une deuxième colonne.

## Vérification de la cohérence des colonnes après encodage

In [55]:
print(X_train.shape)
print(X_test.shape)

colonnes_manquantes_train = set(X_test.columns) - set(X_train.columns)
colonnes_manquantes_test = set(X_train.columns) - set(X_test.columns)

print("Colonnes dans test mais pas dans train :", colonnes_manquantes_train)
print("Colonnes dans train mais pas dans test :", colonnes_manquantes_test)

(491, 18)
(123, 17)
Colonnes dans test mais pas dans train : set()
Colonnes dans train mais pas dans test : {'Married_No'}


**Commentaire :** `X_train` et `X_test` ont été encodés séparément, ce qui peut créer un décalage si une catégorie rare n'apparaît que dans l'un des deux jeux de données. Ici, `Married_No` s'est retrouvée uniquement dans `X_train` (18 colonnes) et absente de `X_test` (17 colonnes). un modèle entraîné sur 18 colonnes ne peut pas prédire sur un tableau à 17.

## Correction de l'incoherance des colonnes après encodage 

In [56]:
X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)

print(X_train.shape)
print(X_test.shape)

(491, 18)
(123, 18)


**Commentaire :** `align()` force `X_test` à avoir exactement les mêmes colonnes que `X_train`, dans le même ordre, en complétant la colonne manquante (`Married_No`) avec des 0. Les deux jeux ont maintenant 18 colonnes chacun, prêts pour l'entraînement.

## Choix des modèles de classification

Pour ce projet de scoring de crédit, deux contraintes nous orientent directement le choix des modèles :

1. **La réduction des Faux Négatifs est prioritaire** : un mauvais payeur classé à tort comme "bon payeur" (Faux Négatif) coûte plus cher à la banque qu'un bon payeur refusé par erreur (Faux Positif). 

2. **L'interprétabilité est exigée**  : dans un contexte bancaire réglementé, un refus de crédit doit pouvoir être expliqué au client. Cela exclut d'office les modèles dits "boîte noire", c'est-à-dire les modèles qui produisent une prédiction sans qu'on puisse reconstruire le raisonnement qui y mène (l'inverse d'un modèle interprétable, où chaque variable a un poids ou une règle qu'on peut lire et expliquer).

C'est pourquoi nous avons retenu 3 modèles, tous interprétables, mais avec des logiques complémentaires :

### 1. Régression Logistique
Modèle de référence ("baseline") : rapide à entraîner, et chaque variable obtient un coefficient clair : un chiffre positif ou négatif qui indique directement dans quel sens et avec quelle intensité elle influence la probabilité d'accord ou de refus. 

### 2. Arbre de Décision
Le modèle le plus transparent des trois : sa structure entière peut être visualisée comme une suite de questions successives, ce qui permet d'expliquer une décision individuelle à un client de façon très concrète. En contrepartie, un arbre non limité en profondeur risque de sur-apprendre les données d'entraînement.

### 3. Random Forest
Une moyenne de nombreux arbres de décision, généralement plus performante et plus robuste qu'un arbre seul, tout en restant interprétable grâce à `feature_importances_`, qui indique quelles variables pèsent le plus dans les décisions du modèle, en moyenne sur l'ensemble des arbres. C'est un bon compromis entre performance et transparence.

**Modèles écartés :** KNN a été exclu car il n'offre aucune interprétabilité (pas de coefficients ni d'importance de variables) et gère mal le mélange de variables catégorielles et numériques présent dans ce dataset. Le SVM a également été écarté, pour les mêmes raisons de faible interprétabilité par défaut.

### Régression Logistique (Laurie)

In [57]:
from sklearn.preprocessing import StandardScaler
scaler_reg = StandardScaler()

X_train_scaled = scaler_reg.fit_transform(X_train)       
X_test_scaled = scaler_reg.transform(X_test)   

In [58]:
from sklearn.linear_model import LogisticRegression

model_1 = LogisticRegression(class_weight='balanced', random_state=42)

In [59]:
model_1.fit(X_train_scaled, y_train)

,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",'balanced'
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",42
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default

Classes : ['N' 'Y']
Prédictions : ['N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'Y' 'N'
 'N' 'Y' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y'
 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'N' 'Y'
 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y'
 'Y' 'N' 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'Y' 'N']
Probabilités :
[[0.93296122 0.06703878]
 [0.20533152 0.79466848]
 [0.41294638 0.58705362]
 [0.47338144 0.52661856]
 [0.21019791 0.78980209]
 [0.1486251  0.8513749 ]
 [0.23360134 0.76639866]
 [0.34338362 0.65661638]
 [0.2552353  0.7447647 ]
 [0.21931601 0.78068399]
 [0.2478902  0.7521098 ]
 [0.23225485 0.76774515]
 [0.28353586 0.71646414]
 [0.36946931 0.63053069]
 [0.95298563 0.04701437]
 [0.9306649  0.0693351 ]
 [0.26997216 0.73002784]
 [0.85470607 0.14529393]
 

In [62]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

print("Accuracy (Performance globale) :", accuracy_score(y_test, y_pred_model_1))
print("Précision (Fiabilité des 'N') :", precision_score(y_test, y_pred_model_1, pos_label='N'))
print("Rappel / Recall (Sécurité 'N') :", recall_score(y_test, y_pred_model_1, pos_label='N'))
print("F1-Score (Compromis pour 'N') :", f1_score(y_test, y_pred_model_1, pos_label='N'))


print("MATRICE DE CONFUSION")
print(confusion_matrix(y_test, y_pred_model_1))
print("RAPPORT DE CLASSIFICATION COMPLET")
print(classification_report(y_test, y_pred_model_1))

Accuracy (Performance globale) : 0.8617886178861789
Précision (Fiabilité des 'N') : 0.9565217391304348
Rappel / Recall (Sécurité 'N') : 0.5789473684210527
F1-Score (Compromis pour 'N') : 0.7213114754098361
MATRICE DE CONFUSION
[[22 16]
 [ 1 84]]
RAPPORT DE CLASSIFICATION COMPLET
              precision    recall  f1-score   support

           N       0.96      0.58      0.72        38
           Y       0.84      0.99      0.91        85

    accuracy                           0.86       123
   macro avg       0.90      0.78      0.81       123
weighted avg       0.88      0.86      0.85       123



In [63]:
import matplotlib.pyplot as plt

feature_names = list(X_train.columns)            # Converti en liste pour le append
coefficients = list(model_1.coef_[0])            # [0] extrait la liste simple des coefficients
intercept = model_1.intercept_[0]                # [0] extrait la valeur numérique de l'intercept


feature_names.append("INTERCEPT (Biais)")
coefficients.append(intercept)


plt.figure(figsize=(10, 6))
plt.barh(feature_names, coefficients, color='steelblue')
plt.axvline(x=0, color='black', linestyle='--')
plt.xlabel("Importance des Coefficients")
plt.title("Importance des Caractéristiques dans le modèle de Régression Logistique")
plt.show()

### Arbre de décision (Davit)

##### 1.  Prediction

In [64]:
from sklearn.tree import DecisionTreeClassifier

model_dtc = DecisionTreeClassifier(random_state=0, max_depth=None, min_samples_split=2, criterion ='gini')
xtrain=X_train.to_numpy()
ytrain=y_train.to_numpy()
model_dtc.fit(xtrain, ytrain)

xtest=X_test.to_numpy()
ytest=y_test.to_numpy()

prediction_dtc=model_dtc.predict(xtest)
diffs=ytest[ytest!=prediction_dtc]
print("Test y targets:", ytest)
print("Les predictions :", prediction_dtc)
print("Score précisions:", 1-len(diffs)/len(ytest))

Test y targets: ['N' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'Y' 'N'
 'N' 'Y' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y'
 'Y' 'Y' 'N' 'Y' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'Y' 'N' 'Y'
 'N' 'N' 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N'
 'Y' 'N' 'N' 'Y' 'Y' 'N' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y'
 'N' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'N' 'N' 'Y' 'Y' 'N' 'N' 'Y' 'N']
Les predictions : ['N' 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'N' 'N'
 'N' 'Y' 'N' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y'
 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'N' 'Y'
 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'N' 'N' 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'N' 'Y' 'Y' 'N'
 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'N' 'Y' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y'
 'N' 'N' 'N' 'Y' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'N'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y'

##### 2.  Interpretation

In [65]:
import matplotlib.pyplot as plt
importances = model_dtc.feature_importances_  # Importance
feature_names = X_train.columns
plt.figure(figsize=(10, 6))
plt.barh(feature_names, importances)
plt.xlabel("Importance des Caractéristiques")
plt.title("Importance des Caractéristiques dans un Modèle l'Arbe de Décision")

Text(0.5, 1.0, "Importance des Caractéristiques dans un Modèle l'Arbe de Décision")

##### 3. Evolution

###### 3.1 Matrice de confusion

In [66]:
# Matrice de Confusion
from sklearn import metrics
print(ytest, "les valuers rééles")
print(prediction_dtc, "les prédictions")
score = metrics.confusion_matrix(ytest, prediction_dtc)

print(score)

['N' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'Y' 'N'
 'N' 'Y' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y'
 'Y' 'Y' 'N' 'Y' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'Y' 'N' 'Y'
 'N' 'N' 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N'
 'Y' 'N' 'N' 'Y' 'Y' 'N' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y'
 'N' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'N' 'N' 'Y' 'Y' 'N' 'N' 'Y' 'N'] les valuers rééles
['N' 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'N' 'N'
 'N' 'Y' 'N' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y'
 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'N' 'Y'
 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'N' 'N' 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'N' 'Y' 'Y' 'N'
 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'N' 'Y' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y'
 'N' 'N' 'N' 'Y' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'N'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y

###### 3.2 Métriques d'evaluation en classification

3.2.1 Accuracy

In [67]:
accuracy = metrics.accuracy_score(ytest, prediction_dtc)
print(accuracy)

0.7479674796747967


3.2.2 Précision

In [68]:
Précision = metrics.precision_score(ytest, prediction_dtc, average='macro')
print(Précision)

0.7055860805860805


3.2.3 Rapel

In [69]:
rappel = metrics.recall_score(ytest, prediction_dtc, average='macro')
print(rappel)

0.708513931888545


3.2.4 F1-Score

In [70]:
f1_score = metrics.f1_score(ytest, prediction_dtc, average='macro')
print(f1_score)

0.7069853223699377


## Random Forest (Zohair)

**Pourquoi ce modèle n'a pas besoin de standardisation :** la Random Forest ne calcule pas de distances entre points (contrairement à KNN ou la régression logistique), donc l'échelle des variables n'a pas d'impact. on utilise `X_train`/`X_test` bruts, pas de version `_scaled`. On garde `random_state=42` pour que le résultat soit reproductible d'une exécution à l'autre.

In [71]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(random_state=42)
model_rf.fit(X_train, y_train)

y_pred_rf = model_rf.predict(X_test)
y_pred_rf

array(['N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y',
       'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y',
       'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'N', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N',
       'Y', 'Y', 'N', 'N', 'Y', 'N'], dtype=object)

## Évaluation : Random Forest

In [72]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

print("Accuracy :", accuracy_score(y_test, y_pred_rf))
print("Précision (macro) :", precision_score(y_test, y_pred_rf, average='macro'))
print("Rappel (macro) :", recall_score(y_test, y_pred_rf, average='macro'))
print("F1 (macro) :", f1_score(y_test, y_pred_rf, average='macro'))
print(classification_report(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))

Accuracy : 0.8373983739837398
Précision (macro) : 0.8247311827956989
Rappel (macro) : 0.7804953560371517
F1 (macro) : 0.7967614011896893
              precision    recall  f1-score   support

           N       0.80      0.63      0.71        38
           Y       0.85      0.93      0.89        85

    accuracy                           0.84       123
   macro avg       0.82      0.78      0.80       123
weighted avg       0.83      0.84      0.83       123

[[24 14]
 [ 6 79]]


**Pourquoi regarder le rappel par classe, pas juste l'accuracy :** Avec mon équipe, on a décidé de prioriser la réduction des Faux Négatifs. Avec une accuracy de 0.84, le modèle a l'air globalement bon. mais le détail par classe révèle que le rappel sur N (refusé/à risque) n'est que de 0.63 : sur 38 vrais mauvais payeurs, 14 ont été classés à tort comme "Y" (bon payeur). C'est cette erreur précise, la plus coûteuse pour la banque, qu'il faut surveiller en priorité et l'accuracy seule l'aurait masquée.

## Importance des variables : Random Forest

In [73]:
import pandas as pd

importances = pd.Series(model_rf.feature_importances_, index=X_train.columns).sort_values(ascending=False)
importances

Credit_History             0.231921
ApplicantIncome            0.201389
LoanAmount                 0.178639
CoapplicantIncome          0.107551
Loan_Amount_Term           0.047527
Property_Area_Semiurban    0.028772
Education_Not Graduate     0.026429
Property_Area_Urban        0.024282
Dependents_1               0.023885
Gender_Male                0.020864
Dependents_2               0.019365
Self_Employed_No           0.018006
Self_Employed_Yes          0.016250
Dependents_3+              0.015119
Married_Yes                0.014965
Married_No                 0.013546
Gender_Inconnu             0.007003
Dependents_Inconnu         0.004489
dtype: float64

**Pourquoi cette étape :** `feature_importances_` indique quelles variables pèsent le plus dans les décisions du modèle, en moyenne sur tous les arbres de la forêt. `Credit_History` arrive en tête (0.23). `ApplicantIncome` et `LoanAmount` pèsent aussi beaucoup ici, alors que l'EDA univariée seule ne les montrait pas comme très discriminantes. Preuve que l'importance d'une variable en isolation ne reflète pas toujours son poids réel dans un modèle qui combine plusieurs variables à la fois.

## Random Forest  avec class_weight balanced (comparaison)

In [74]:
model_rf_balanced = RandomForestClassifier(random_state=42, class_weight='balanced')
model_rf_balanced.fit(X_train, y_train)
y_pred_rf_balanced = model_rf_balanced.predict(X_test)

print(classification_report(y_test, y_pred_rf_balanced))

              precision    recall  f1-score   support

           N       0.76      0.68      0.72        38
           Y       0.87      0.91      0.89        85

    accuracy                           0.84       123
   macro avg       0.81      0.80      0.80       123
weighted avg       0.83      0.84      0.83       123



**Pourquoi tester cette variante :** face au déséquilibre des classes (68.7% Y / 31.3% N) et notre  priorité  sur les Faux Négatifs, `class_weight='balanced'` pénalise davantage les erreurs sur la classe minoritaire (N) pendant l'entraînement. Résultat : le rappel sur N monte de 0.63 à 0.68 (moins de mauvais payeurs ratés), au prix d'une légère baisse de précision sur N (0.80 → 0.76).
Le modèle devient un peu plus "méfiant", donc accuse à tort un peu plus de bons payeurs. 
L'accuracy globale reste identique (0.84) dans les deux cas, ce qui confirme qu'elle ne suffit pas à elle seule pour départager ces deux versions.

## Tableau comparatif des modèles

In [99]:
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

predictions = {
    "Régression Logistique": y_pred_model_1,
    "Arbre de Décision": prediction_dtc,              
    "Random Forest": y_pred_rf,
    "Random Forest (balanced)": y_pred_rf_balanced,
}

resultats = []
for nom, y_pred in predictions.items():
    resultats.append({
        "Modèle": nom,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Précision (macro)": precision_score(y_test, y_pred, average='macro'),
        "Rappel (macro)": recall_score(y_test, y_pred, average='macro'),
        "Rappel classe N": recall_score(y_test, y_pred, pos_label='N'),
        "F1 (macro)": f1_score(y_test, y_pred, average='macro'),
    })

resultats_df = pd.DataFrame(resultats)
resultats_df

,Modèle,Accuracy,Précision (macro),Rappel (macro),Rappel classe N,F1 (macro)
0,Régression Logistique,0.861789,0.898261,0.783591,0.578947,0.814710
1,Arbre de Décision,0.747967,0.705586,0.708514,0.605263,0.706985
2,Random Forest,0.837398,0.824731,0.780495,0.631579,0.796761
3,Random Forest (balanced),0.837398,0.814937,0.795046,0.684211,0.803640


In [100]:
import matplotlib.pyplot as plt

# On visualise le Rappel classe N (part des mauvais payeurs correctement détectés)
# car c'est le critère de choix prioritaire du brief : un mauvais payeur non repéré
# (faux négatif) coûte plus cher à la banque qu'un bon payeur refusé à tort (faux positif).
# L'accuracy globale passe donc en critère secondaire.
plt.figure(figsize=(8, 5))
bars = plt.bar(resultats_df["Modèle"], resultats_df["Rappel classe N"], color="#4C72B0")

for bar in bars:
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02,
              f"{bar.get_height():.2f}", ha="center")

# Random Forest (balanced) l'emporte (0.684) malgré une accuracy un peu plus faible
# que la Régression Logistique (0.837 vs 0.862) : c'est le compromis recherché,
# on préfère détecter plus de mauvais payeurs quitte à refuser à tort quelques bons profils.
plt.ylim(0, 1)
plt.ylabel("Rappel classe N")
plt.title("Rappel classe N par modèle (critère de choix prioritaire)")
plt.xticks(rotation=15)
plt.tight_layout()
plt.show()

### Choix du modèle final : Random Forest (balanced)

Le brief priorise la réduction des faux négatifs : un mauvais payeur non détecté coûte plus cher à la banque qu'un bon payeur refusé à tort. Le **rappel sur la classe N** est donc le critère de choix principal, pas l'accuracy globale.

Avec un rappel classe N de **0.684**, contre 0.579 (Régression Logistique), 0.605 (Arbre de Décision) et 0.632 (Random Forest standard), le Random Forest balanced est le modèle qui détecte le mieux les mauvais payeurs. même si l' accuracy est légèrement inférieure (0.837 vs 0.862 pour la Régression Logistique). C'est un compromis assumé par notre équipe, cohérent avec l'objectif métier.